AWSTemplateFormatVersion: "2010-09-09"
Description: Testing bucket creation using CloudFormation

Parameters:
  BucketName:
    Type: String
    Default: raashed-cf-s3-bucket
  KmsKeyArn:
    Type: String
    Default: arn:aws:kms:ap-south-1:591446361969:key/fbada760-4de5-4d9b-8305-b15208383337

Resources:
  MainBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
              KMSMasterKeyID: !Ref KmsKeyArn
      VersioningConfiguration:
        Status: Enabled

Outputs:
  MainBucketName:
    Description: name of the main bucket
    Value: !Ref BucketName
